SELECT S.NPOLIZA poliza,PA.NNUMIDE rut,s.sproduc producto, S.NCERTIF certificado, S.SSEGURO,  PG.NRIESGO,PG.CGARANT codigo_cobertura_iaxis, 
PE. TPREGUN tipo_recargo, PG. CRESPUE valor_recargo, pg.finiefe fecha_ini_recargo
FROM SEGUROS S  inner JOIN PREGUNGARANSEG PG ON  S.SSEGURO = PG.SSEGURO AND PG.NMOVIMI = (SELECT  MAX(PG2.NMOVIMI) FROM PREGUNGARANSEG PG2 WHERE PG2.SSEGURO = S.SSEGURO  )
           inner JOIN PREGUNTAS PE  ON PG.CPREGUN =  PE.CPREGUN  AND PE.CIDIOMA = 3
           inner JOIN ASEGURADOS A ON S.SSEGURO = A.SSEGURO
           inner JOIN PER_PERSONAS PA  ON PA.SPERSON = A.SPERSON
WHERE PG.CPREGUN IN(9195, 9207) 
AND PG.CRESPUE>0