SELECT CIERRE, POL_PROD, COBCOD, PERIODO_INI, RVAPOLTIP,
SUM(RRC_DIRECTA_LOCAL) as RRC_DIRECTA_LOCAL, sum(RRC_CEDIDA_LOCAL) as RRC_CEDIDA_LOCAL,
sum(RRC_DIRECTA_IFRS) as RRC_DIRECTA_IFRS, sum(RRC_CEDIDA_IFRS) as RRC_CEDIDA_IFRS
from 
(
select RVAPROCANO, RVAPROCMES,
RVAPROCANO*100 + RVAPROCMES as CIERRE,
CASE WHEN RVAPOLTIP  = 'I' THEN RVAPROD ELSE POLNUM  END AS POL_PROD,
COBCOD, RVAPOLTIP, extract (year from RVAVIIFRS)*100+extract (month from RVAVIIFRS) AS PERIODO_INI,
RVARRCNETA RRC_DIRECTA_LOCAL,RVARRCCED RRC_CEDIDA_LOCAL,
RVAPRINETNDEV RRC_DIRECTA_IFRS,RVAPRICEDNDEV RRC_CEDIDA_IFRS
from general.RvaDet
where RVAPROCANO = año_proceso
and RVAPROCMES = mes_proceso
)
where RRC_CEDIDA_LOCAL >0 
and cobcod in (94,7800,7810,7820)
group by CIERRE, POL_PROD, COBCOD, RVAPOLTIP, PERIODO_INI
order by POL_PROD
