site_name: Documentacion
site_url: http://Documentacion_Renovacion:Reaseguro.com
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange


nav:
  - Clase Loaders: S0_Loaders.md
  - Parametros de Calculo: S1_Parametros_Calculo.md
  - Funciones: S2_Funciones.md
  - Preprocesamiento: S3_Pre_Procesamiento.md
  - Renovacion: S4_Calculos_Renovacion.md
  - Funcion Principal: S5_Automatizacion_Calculos.md
  - Docstrings: Docstrings.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy

