site_name: Documentacion
site_url: http://Documentacion_Renovacion:Reaseguro.com
theme:
  name: material
  features:
    - navigation.footer  # Para anotaciones
  font:
    text: Raleway
    code: Red Hat Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      use_pygments: true  # Activa Pygments
      anchor_linenums: true
      line_spans: __span
      linenums: true
      pygments_style: monokai  # Cambia "monokai" por el tema que prefieras
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
extra_css:
  - extra.css


nav:
  - Clase Loaders: S0_Loaders.md
  - Parametros de Calculo: S1_Parametros_Calculo.md
  - Funciones: S2_Funciones.md
  - Preprocesamiento: S3_Pre_Procesamiento.md
  - Renovacion: S4_Calculos_Renovacion.md
  - Funcion Principal: S5_Automatizacion_Calculos.md
  - Docstrings: Docstrings.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy

